version: '3'
services:
  api:
    build: backend
    environment:
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
    depends_on:
      - db
  db:
    build: postgres
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data
  web:
    build: nginx
    ports:
      - 3000:80
    volumes:
      - ./nginx/log:/var/log/nginx
    volumes_from:
      - api
    depends_on:
      - api
  view:
    build: frontend
    ports:
      - 8080:8080

volumes:
  postgres-data:
