version: '3'
services:
  api:
    build: backend
    environment:
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
    volumes:
      - type: bind
        source: ./backend
        target: /backend
      - type: volume
        source: api-public-data
        target: /backend/public
      - type: volume
        source: api-tmp-data
        target: /backend/tmp
      - type: volume
        source: api-log-data
        target: /backend/log
    stdin_open: true
    tty: true
    depends_on:
      - db
  db:
    build: postgres
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data
  web:
    build: nginx
    ports:
      - 3000:80
    volumes:
      - ./nginx/log:/var/log/nginx
      - api-public-data:/backend/public
      - api-tmp-data:/backend/tmp
    depends_on:
      - api
  view:
    build: frontend
    ports:
      - 8080:8080
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: ./frontend
        target: /frontend
    #   - type: volume
    #     source: view-log-data
    #     target: /frontend/log


volumes:
  postgres-data:
  api-public-data:
  api-tmp-data:
  api-log-data:
  # view-log-data:
