name: Rspec_Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12.5
        ports: ["5432:5432"]
        # options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        env:
          DATABASE_HOST: postgres
          POSTGRES_PASSWORD: password
          # POSTGRES_HOST_AUTH_METHOD: 'trust'
    container:
      image: ruby:2.6.5
      env:
        RAILS_ENV: test
        DATABASE_HOST: postgres

    steps:
    - uses: actions/checkout@v2
    - name: Install Bundler
      run: gem install bundler --no-document -v $(grep "BUNDLED WITH" -1 Gemfile.lock | tail -n 1)
      working-directory: ./backend
    - name: Bundle install
      run: bundle install --path=vendor/bundle --jobs 4 --retry 3
      working-directory: ./backend
    - name: DB create
      run: bundle exec rails db:create
      working-directory: ./backend
    - name: DB migrate
      run: bundle exec rails db:migrate
      working-directory: ./backend
    - name: Run rspec
      run: bundle exec rspec
      working-directory: ./backend
