name: Exec RuboCop

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
# on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      working-directory: ./backend
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      working-directory: ./backend
      with:
        ruby-version: 2.6.5
        bundler-cache: true
    - name: Run RuboCop
      run: bundle exec rubocop
      working-directory: ./backend
